import { Product, StoreSection, SecurityEvent } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-milk',
    name: 'Organic Farm Milk 3.2%',
    nameRu: 'Молоко Фермерское Органическое 3.2%',
    nameKz: 'Органикалық Ферма Сүті 3.2%',
    price: 850,
    weight: 1000,
    barcode: '4870201010041',
    rfid: 'RFID-MILK-900',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=400',
    category: 'dairy',
    calories: 60,
    proteins: 3.2,
    fats: 3.2,
    carbs: 4.7,
    filters: {
      vegan: false,
      halal: true,
      organic: true,
      glutenFree: true,
      sugarFree: true,
      eco: true
    },
    description: 'Fresh organic pasteurized milk directly from green pastures in Almaty region.',
    descriptionRu: 'Свежее органическое пастеризованное молоко напрямую с зеленых пастбищ Алматинской области.',
    descriptionKz: 'Алматы облысының жасыл жайылымдарынан алынған балғын органикалық пастерленген сүт.'
  },
  {
    id: 'prod-bread',
    name: 'Whole Wheat Sourdough Bread',
    nameRu: 'Хлеб Цельнозерновой на закваске',
    nameKz: 'Тұтас Тұқымды Ашытқы Нан',
    price: 490,
    weight: 450,
    barcode: '4870201010089',
    rfid: 'RFID-BREAD-205',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    category: 'bakery',
    calories: 240,
    proteins: 8.5,
    fats: 1.2,
    carbs: 48.0,
    filters: {
      vegan: true,
      halal: true,
      organic: true,
      glutenFree: false,
      sugarFree: true,
      eco: false
    },
    description: 'Artisanal stone-baked wheat sourdough bread with no artificial yeast.',
    descriptionRu: 'Ремесленный хлеб на закваске, выпеченный на камне без добавления дрожжей.',
    descriptionKz: 'Табиғи ашытқыдан дайындалған, тас пеште пісірілген қолөнер наны.'
  },
  {
    id: 'prod-steak',
    name: 'Premium Angus Ribeye Steak (Halal)',
    nameRu: 'Стейк Рибай Премиум Ангус (Халал)',
    nameKz: 'Премиум Ангус Рибай Стейкі (Халал)',
    price: 6800,
    weight: 350,
    barcode: '4870201010126',
    rfid: 'RFID-STEAK-350',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
    category: 'meat',
    calories: 290,
    proteins: 22.0,
    fats: 22.0,
    carbs: 0.0,
    filters: {
      vegan: false,
      halal: true,
      organic: true,
      glutenFree: true,
      sugarFree: true,
      eco: false
    },
    description: 'Grain-fed local Angus beef ribeye steak, certified Halal, beautifully marbled.',
    descriptionRu: 'Стейк рибай из зернового откорма местной говядины Ангус, сертифицированный Халал.',
    descriptionKz: 'Дәнді откормдағы жергілікті Ангус сиыр етінен рибай стейк, Халал сертификаты бар.'
  },
  {
    id: 'prod-berries',
    name: 'Fresh Organic Blueberries',
    nameRu: 'Свежая Органическая Голубика',
    nameKz: 'Балғын Органикалық Көкжидек',
    price: 1850,
    weight: 125,
    barcode: '4870201010256',
    rfid: 'RFID-BERRY-125',
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=400',
    category: 'produce',
    calories: 57,
    proteins: 0.7,
    fats: 0.3,
    carbs: 14.0,
    filters: {
      vegan: true,
      halal: true,
      organic: true,
      glutenFree: true,
      sugarFree: true,
      eco: true
    },
    description: 'Antioxidant-rich fresh organic blueberries packed in biodegradable craft boxes.',
    descriptionRu: 'Богатая антиоксидантами свежая органическая голубика в биоразлагаемой крафтовой коробочке.',
    descriptionKz: 'Антиоксиданттарға бай балғын органикалық көкжидек, экологиялық таза қорапта.'
  },
  {
    id: 'prod-cookies',
    name: 'Gluten-Free Sugarless Vegan Cookies',
    nameRu: 'Печенье Без Глютена, Сахара и Веган',
    nameKz: 'Глютенсіз және Қантсыз Веган Печеньесі',
    price: 1200,
    weight: 200,
    barcode: '4870201010324',
    rfid: 'RFID-COOKIE-200',
    image: 'https://images.unsplash.com/photo-1558961309-db6fce6c554e?auto=format&fit=crop&q=80&w=400',
    category: 'snacks',
    calories: 320,
    proteins: 5.0,
    fats: 14.0,
    carbs: 45.0,
    filters: {
      vegan: true,
      halal: true,
      organic: false,
      glutenFree: true,
      sugarFree: true,
      eco: true
    },
    description: 'Delicious almond and coconut flour cookies sweetened with natural monkfruit extract.',
    descriptionRu: 'Вкуснейшее овсяно-миндальное печенье без обычного сахара, подслащенное экстрактом монкфрута.',
    descriptionKz: 'Қантсыз жасалған, монкфрут сығындысымен тәттіленген бадам және кокос ұны печеньесі.'
  },
  {
    id: 'prod-avocado',
    name: 'Hass Premium Avocado (2 Pack)',
    nameRu: 'Авокадо Хасс Премиум (2 штуки)',
    nameKz: 'Хасс Премиум Авокадо (2 дана)',
    price: 1450,
    weight: 320,
    barcode: '4870201010904',
    rfid: 'RFID-AVOCADO-320',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&q=80&w=400',
    category: 'produce',
    calories: 160,
    proteins: 2.0,
    fats: 15.0,
    carbs: 9.0,
    filters: {
      vegan: true,
      halal: true,
      organic: true,
      glutenFree: true,
      sugarFree: true,
      eco: true
    },
    description: 'Perfectly ripe, creamy Hass avocados high in heart-healthy monounsaturated fats.',
    descriptionRu: 'Идеально спелые, кремовые авокадо Хасс с высоким содержанием полезных жиров.',
    descriptionKz: 'Жүрекке пайдалы майлары көп, толық піскен, қаймақтай жұмсақ Хасс авокадосы.'
  },
  {
    id: 'prod-water',
    name: 'Turan Natural Mineral Water 1L',
    nameRu: 'Минеральная вода Turan 1л',
    nameKz: 'Turan Табиғи Минералды Суы 1л',
    price: 320,
    weight: 1000,
    barcode: '4870201010416',
    rfid: 'RFID-TURAN-1000',
    image: 'https://images.unsplash.com/photo-1560011961-4ab41261de01?auto=format&fit=crop&q=80&w=400',
    category: 'drinks',
    calories: 0,
    proteins: 0,
    fats: 0,
    carbs: 0,
    filters: {
      vegan: true,
      halal: true,
      organic: false,
      glutenFree: true,
      sugarFree: true,
      eco: true
    },
    description: 'Physiologically structured natural spring mineral water from direct Borovoe wells.',
    descriptionRu: 'Физиологически структурированная природная родниковая вода непосредственно из источников Борового.',
    descriptionKz: 'Бурабайдың тікелей бұлақ көздерінен алынған физиологиялық құрылымды табиғи минералды су.'
  },
  {
    id: 'prod-protein',
    name: 'WHEY High Isol-Protein Shake (Halal)',
    nameRu: 'Протеиновый Изолят Шейк WHEY (Халал)',
    nameKz: 'WHEY Протеинді Изолят Шейк (Халал)',
    price: 2400,
    weight: 500,
    barcode: '4870201010553',
    rfid: 'RFID-WHEY-500',
    image: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&q=80&w=400',
    category: 'fitness',
    calories: 120,
    proteins: 26.0,
    fats: 1.0,
    carbs: 2.0,
    filters: {
      vegan: false,
      halal: true,
      organic: false,
      glutenFree: true,
      sugarFree: true,
      eco: false
    },
    description: 'Ultra-filtered premium sports whey protein with natural strawberry and stevia vanilla.',
    descriptionRu: 'Ультрафильтрованный сывороточный протеин премиум-класса с натуральной клубникой и стевией.',
    descriptionKz: 'Табиғи құлпынай мен стевия қосылған ультрасүзгіден өткен премиум спорттық протеин.'
  }
];

export const MAP_SECTIONS: StoreSection[] = [
  { id: 'sec-dairy', name: 'Dairy & Milk Products', nameRu: 'Молочный Отдел', nameKz: 'Сүт Өнімдері Бөлімі', x: 20, y: 30, color: 'border-blue-500 bg-blue-950/40 text-blue-400', category: 'dairy' },
  { id: 'sec-bakery', name: 'Artisan Bakery', nameRu: 'Свежая Выпечка', nameKz: 'Нан-Тоқаш Бөлімі', x: 80, y: 25, color: 'border-amber-500 bg-amber-950/40 text-amber-400', category: 'bakery' },
  { id: 'sec-meat', name: 'Halal Meat & Poultry', nameRu: 'Мясной Отдел & Халал', nameKz: 'Ет және Халал Өнімдері', x: 50, y: 20, color: 'border-red-500 bg-red-950/40 text-red-400', category: 'meat' },
  { id: 'sec-drinks', name: 'Pure Water & Drinks', nameRu: 'Напитки & Соки', nameKz: 'Сусындар Мекені', x: 15, y: 75, color: 'border-teal-500 bg-teal-950/40 text-teal-400', category: 'drinks' },
  { id: 'sec-snacks', name: 'Organic Snacks & Bites', nameRu: 'Бакалея & Закуски', nameKz: 'Тәттілер мен Снэктер', x: 50, y: 80, color: 'border-purple-500 bg-purple-950/40 text-purple-400', category: 'snacks' },
  { id: 'sec-produce', name: 'Fresh Fruits & Greens', nameRu: 'Овощи & Фрукты', nameKz: 'Жеміс-Жидек және Көкөністер', x: 80, y: 70, color: 'border-green-500 bg-green-950/40 text-green-400', category: 'produce' },
  { id: 'sec-fitness', name: 'Healthy Alternatives & Fitness', nameRu: 'ПП & Спортивное Питание', nameKz: 'ПП және Спорттық Тағамдар', x: 50, y: 50, color: 'border-lime-500 bg-emerald-950/40 text-lime-400', category: 'fitness' }
];

export const INITIAL_SECURITY_ALERTS: SecurityEvent[] = [
  {
    id: 'sec-evt-1',
    type: 'weight_mismatch',
    message: 'Smart Plate weight discrepancy detected! Item on plate (+1000g) does not match the catalog scanning details of Whole Wheat Bread (+450g). Please adjust or verify.',
    messageRu: 'Обнаружено весовое несовпадение! Вес товара на платформе (+1000г) не совпадает с весом Хлеба (+450г). Пожалуйста, проверьте товар.',
    severity: 'medium',
    timestamp: '09:28:44',
    resolved: false
  },
  {
    id: 'sec-evt-2',
    type: 'age_restriction',
    message: 'Age verification requested via QR/eGov for premium meat processing tools. Approval complete.',
    messageRu: 'Маркировка возраста запрошена через eGov QR для мясной нарезки. Подтверждение пройдено успешно.',
    severity: 'low',
    timestamp: '09:12:05',
    resolved: true
  }
];

export const LOCALIZATION = {
  en: {
    welcome: 'Welcome to Q-GO Smart Shopping',
    greeting: 'Hello, Dynamic Shopper!',
    startShopping: 'Start Shopping',
    totalText: 'Active Cart Total',
    itemCount: 'Items Count',
    quickPay: 'Proceed to Payment',
    promotions: 'Hot Promos & Seasonal Offers',
    searchPlaceholder: 'Search for milk, protein, steak...',
    specialFilters: 'Precision Smart Filters',
    cartCaption: 'Your Smart Cart Ecosystem',
    alternativeTitle: 'AI Healthy & Smart Alternatives',
    navigationTitle: 'Floor Plan Live Navigator',
    adminTitle: 'Q-GO Store Management & Heatmap Engine',
    inclusiveModeLabel: 'Inclusive Mode presets (Large print, high contrast)',
    voiceActive: 'Speech Assistant listening...',
    ecoSavings: 'Your Eco-Ecosystem Savings Tracking',
    savingMetrics: 'Eco-Points Accrued',
    plasticSaved: 'Plastic Waste Saved',
    carbonSaved: 'Carbon Emissions Prevented',
    secAlertsTitle: 'AI Anti-Theft & Object Verification Systems',
    egovCheck: 'Verify Identity via Kaspi/eGov QR',
    languageNamePrefix: 'Language: English',
    companionAppTitle: 'Mobile Companion App Synchronizer',
    loyaltyPoints: 'Loyalty Tier Status'
  },
  ru: {
    welcome: 'Добро пожаловать в smart-экосистему Q-GO',
    greeting: 'Здравствуйте, Умный Покупатель!',
    startShopping: 'Начать Покупки',
    totalText: 'Сумма к оплате',
    itemCount: 'Всего товаров',
    quickPay: 'Перейти к Оплате (PayPad)',
    promotions: 'Персональные акции и рекомендации',
    searchPlaceholder: 'Искать молоко, протеин, стейк...',
    specialFilters: 'Умные эко-фильтры продуктов',
    cartCaption: 'Ваша умная корзина покупателя',
    alternativeTitle: 'AI Полезные Альтернативы & Сопутствующие',
    navigationTitle: 'Интерактивная Навигация по Полкам',
    adminTitle: 'Q-GO Панель Управления Магазином и Аналитика',
    inclusiveModeLabel: 'Инклюзивные опции (Крупный текст, речевой гид)',
    voiceActive: 'Ассистент слушает вашу команду...',
    ecoSavings: 'Экологический след & Зеленый чек',
    savingMetrics: 'Накоплено Эко-баллов',
    plasticSaved: 'Сбережено пластика',
    carbonSaved: 'Предотвращено выбросов CO₂',
    secAlertsTitle: 'AI Системы безопасности и контроля веса',
    egovCheck: 'Авторизация возраста через eGov QR',
    languageNamePrefix: 'Язык: Русский',
    companionAppTitle: 'Синхронизация с Мобильным Приложением',
    loyaltyPoints: 'Статус лояльности'
  },
  kk: {
    welcome: 'Q-GO Smart дүкен жүйесіне қош келдіңіз',
    greeting: 'Сәлеметсіз бе, Зерделі Сатып Алушы!',
    startShopping: 'Сауданы Бастау',
    totalText: 'Төлем сомасы',
    itemCount: 'Тауарлар саны',
    quickPay: 'Төлем жасау (PayPad)',
    promotions: 'Жеке акциялар мен ұсыныстар',
    searchPlaceholder: 'Сүт, протеин, стейк іздеу...',
    specialFilters: 'Сүзгілер мен Эко-категориялар',
    cartCaption: 'Сіздің ақылды себетіңіз',
    alternativeTitle: 'AI Дұрыс балама өнімдер мен ұсыныстар',
    navigationTitle: 'Сөрелер арасындағы навигация',
    adminTitle: 'Q-GO Дүкенді басқару және жылу картасы',
    inclusiveModeLabel: 'Инклюзивті режим белсенді (Үлкен мәтін)',
    voiceActive: 'Дауыстық көмекші белсенді...',
    ecoSavings: 'Экологиялық статистика және жасыл чек',
    savingMetrics: 'Жиналған Эко-ұпайлар',
    plasticSaved: 'Үнемделген пластик',
    carbonSaved: 'Жойылған көмірқышқыл газ CO₂',
    secAlertsTitle: 'AI Қауіпсіздік және салмақ дәлдігін тексеру',
    egovCheck: 'eGov QR арқылы жасты растау',
    languageNamePrefix: 'Тіл: Қазақша',
    companionAppTitle: 'Мобильді Қосымшамен Синхрондау',
    loyaltyPoints: 'Лоялдылық деңгейі'
  }
};
